service: clue-websockets

provider:
    name: aws
    runtime: nodejs16.x
    region: us-east-1
    environment:
        tableName: ${self:custom.tableName}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:*
              - "execute-api:ManageConnections"
          Resource: '*'
          
custom:
    tableName: WebsocketUsers

functions:
    websocket-connect:
        handler: lambdas/websockets/connect.handler
        events:
            - websocket:
                  route: $connect
    websocket-disconnect:
        handler: lambdas/websockets/disconnect.handler
        events:
            - websocket:
                  route: $disconnect
    websocket-default:
        handler: lambdas/websockets/default.handler
        events:
            - websocket:
                  route: $default
    websocket-unicast:
        handler: lambdas/websockets/unicast.handler
        events:
            - websocket:
                  route: unicast
    websocket-broadcast:
        handler: lambdas/websockets/broadcast.handler
        events:
            - websocket:
                  route: broadcast
resources:
    Resources:
        WeboscketUserTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: connectionId
                      AttributeType: S
                KeySchema:
                    - AttributeName: connectionId
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
